### ISSUE TITLE
gradle jvm toolchain support

### ISSUE THREAD

**Issue by dsvensson** [gradle/github-dependency-graph-gradle-plugin#137]
When using gradle jvm toolchain feature the build may produce class files that this plugin is unable to read. For example the https://github.com/etiennestuder/gradle-jooq-plugin plugin supports jvm toolchain, which I set to 21/corretto. When running gradle in Github CI it uses an older java to start the gradle daemon, then the jvm toolchain enabled plugin does its stuff in the target jvm, and then this plugin tries to read the class files which fails.

So I think to reproduce this you would do:

* java in path of version 17 or something
* jvm toolchain configured to 21
* use a plugin that is jvm toolchain aware
* try to use this plugin, spot the class file version failure

The workaround for CI would be to install java 21 in a previous step, but it would be convenient if the toolchain was respected, this is a plugin living under the gradle umbrella after all.

**Comment by bigdaz** [comment]
Did you encounter this issue applying the plugin directly, or using the GitHub action?
Can you please try to create a reproducer as a public GitHub project? 
I don't really understand what the issue is.

**Comment by bigdaz** [comment]
I'm unable to reproduce this issue. If you can provide clear instructions to reproduce, I'll be happy to investigate further.
