### ISSUE TITLE
SimpleDependencyGraphPlugin does not capture plugin dependencies

### ISSUE THREAD

**Issue by brianmcgee** [gradle/github-dependency-graph-gradle-plugin#138]
Following the example in the readme, when executing the following, plugin/buildscript dependencies are not being captured. 

```
gradle -I init.gradle --no-configuration-cache --no-configure-on-demand :ForceDependencyResolutionPlugin_resolveAllDependencies
```

It would appear that support for this was added to the `GithubDependencyGraphPlugin` [here](https://github.com/gradle/github-dependency-graph-gradle-plugin/pull/24).

**Comment by bigdaz** [comment]
Why do you believe these dependencies are not being captured? My testing indicates that they are.

Can you please provide a project that allows me to reproduce this issue?

**Comment by brianmcgee** [comment]
@bigdaz here's a repo reproducing what I'm seeing and explaining what I think should be happening https://github.com/brianmcgee/github-dependency-graph-plugin-bug

**Comment by bigdaz** [comment]
Thanks for the reproducer. I'm not sure what's happening on your end, but when I run the exact command against that repo I do see the Spotless Gradle plugin listed in the dependencies:

<img width="507" alt="image" src="https://github.com/gradle/github-dependency-graph-gradle-plugin/assets/179734/968dacb4-0ffc-4581-8efe-ea3bb0e6e5b7">

**Comment by bigdaz** [comment]
You might find it useful to add `--scan` to your invocation: the generated build scan captures all resolved dependencies and is a good way to share your results.

**Comment by brianmcgee** [comment]
I updated my reproducer to include the report I'm generating, which matches what you listed above. I also added a second plugin to demonstrate the issue better.

The report above shows an entry for [com.diffplug.spotless:spotless-plugin-gradle:6.25.0](https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-plugin-gradle/6.25.0/) which is sourced from https://repo.maven.org.

But it does not include an entry for [com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.25.0](https://plugins.gradle.org/m2/com/diffplug/spotless/com.diffplug.spotless.gradle.plugin/6.25.0/) which is sourced from https://plugins.gradle.org. 

Similarly, you will see in my updated example that `com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:8.1.1` is not included in the report.

Here is a scan report for the latest run: https://scans.gradle.com/s/iitusscge3aao

**Comment by bigdaz** [comment]
The specific dependencies you mention are referred to as [plugin marker dependencies](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers). The don't contain any code, and simply help gradle resolve a plugin id to an actual plugin dependency artifact.

These are deliberately and explicitly excluded from the report: https://github.com/gradle/github-dependency-graph-gradle-plugin/issues/111

**Comment by brianmcgee** [comment]
Ah, that makes sense. 

Essentially, if you have a dependency of the form `<group>:<module>-plugin-gradle:<version>` you can reasonably assume the plugin marker to be `<group>:<group>.gradle.plugin:<version>`. 

In answer to why I'm interested in these, I'm using the dependency report from the plugin to construct a lock file for use with [Nix](https://nixos.org) that allows me to construct a local maven repository containing all the build dependencies so the build can be run in offline mode within the Nix sandbox. 

This was the last piece of the puzzle and it looks like I have it working. 

Thanks for your help :pray:

**Comment by bigdaz** [comment]
If it's important to you, I'd be open to a PR that made it possible to retain the plugin marker artifacts via some sort of env var.
Here's where the code is: https://github.com/gradle/github-dependency-graph-gradle-plugin/blob/321383e803910581d412d92e05f6496173cea82c/plugin/src/main/kotlin/org/gradle/dependencygraph/extractor/DependencyExtractor.kt#L248-L262

Any PR would require test coverage.

**Comment by brianmcgee** [comment]
I think my immediate use case is covered, but I'm happy to look at creating a PR to capture them properly. 

I'll try and find some next week to give it a go.
