### ISSUE TITLE
Annotate PRs that merging will resolve or introduce Dependabot alert

### ISSUE THREAD

**Issue by wzieba** [gradle/github-dependency-graph-gradle-plugin#154]
hi there 👋 

#### Context

With some other build systems/managers, e.g. `rubygems`, whenever we create a PR, on top of PR description we get a banner informing that e.g.

<img width="710" alt="image" src="https://github.com/user-attachments/assets/ac54f600-7af4-4cbc-af97-ff3cfcfcc0b9">

this kind of PRs we create directly from `Security` > `Dependabot` > alert details.

#### Question

Would it be possible to have similar behavior with Gradle? I mean:
- if merging a PR would resolve security alert, an info banner is present
- if merging a PR would introduce a security alert, another info banner is present

I've experimented with sending a dependency graph on every push (with changes that were addressing an alert), but no banner was present on PR.

I understand this might be a question/request to GitHub rather than this action, but maybe `github-dependency-graph-gradle-plugin` doesn't send some metadata needed for this feature?

If not with GitHub API, is there maybe another way to annotate that merging PR will resolve or introduce Dependabot alert?

**Comment by bigdaz** [comment]
The `gradle/actions/dependency-submission` action (using this plugin) sends the current dependency graph information to GitHub. This action has no knowledge of changes to the graph, nor of PRs, and I'm not aware of any additional metadata that could be sent.

To annotate a PR, I think you'd need a workflow and action that are specifically targeted at PRs. Do you know how this functionality works for `rubygems`?

**Comment by bigdaz** [comment]
The [dependency-review-action](https://github.com/actions/dependency-review-action) reports on any new vulnerabilities introduced in a PR, using the dependency graph information submitted by `gradle/actions/dependency-submission`. [See here for more details](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#integrating-the-dependency-review-action).

I think `dependency-review-action` be the right place to add functionality that would detect when a PR closes a vulnerability.

**Comment by wzieba** [comment]
Thanks for response @bigdaz !

> The gradle/actions/dependency-submission action (using this plugin) sends the current dependency graph information to GitHub.

Ah sorry, I confused repositories - I thought I'm making issue to the action.

> Do you know how this functionality works for rubygems?

It seems that the label mentioned in the issue is added automatically by GH only when we create a PR by tapping on 
<img width="495" alt="image" src="https://github.com/user-attachments/assets/04f2c79e-836c-4793-9ccd-0a7d99144279">

How this works - I have no idea, and I couldn't find anything in the documentation :/. I'm guessing it's internal for GH.

> The [dependency-review-action](https://github.com/actions/dependency-review-action) reports on any new vulnerabilities introduced in a PR, using the dependency graph information submitted by gradle/actions/dependency-submission. [See here for more details](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#integrating-the-dependency-review-action).

Thank you! That's very helpful. It'd be awesome to have it detecting if a PR closes vulnerability, but reporting on any new vulnerabilities introduced in a PR is already great.

I'm closing the issue then as I understand there's nothing on side of `gradle/actions/dependency-submission` to support the requested feature.
