### ISSUE TITLE
Extract the GitHub model to a separate library

### ISSUE THREAD

**Issue by sschuberth** [gradle/github-dependency-graph-gradle-plugin#25]
It would be nice if other (Kotlin) projects could make use of the GitHub model for submission to the dependency API by extracting it to a separate library for reuse in other projects, like [ORT](https://github.com/oss-review-toolkit/ort/issues/5523).

**Comment by JLLeitschuh** [comment]
Given the model is literally 3 kotlin data classes, I don't know how much value would be added by publishing these independently.

https://github.com/gradle/github-dependency-extractor/tree/main/plugin/src/main/kotlin/org/gradle/github/dependency/extractor/internal/model

**Comment by sschuberth** [comment]
Agreed, it's probably not worth the effort of publishing a separate library.
