### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by jeffalder** [gradle/github-dependency-graph-gradle-plugin#30]
Hi! I was watching this plugin and it really looks like something that would be very useful to us. How can I contribute to it to get it over the finish line? Do you want/need testers? Coders? Test coders?

**Comment by sschuberth** [comment]
I guess testing the quality of the JSON output and providing feedback in the form of issues is always good 😉

**Comment by JLLeitschuh** [comment]
Oh hey!!!! It's finally in the GitHub action!!! That's amazing! I'm thrilled to see that's finally happened!!! 🎉
