### ISSUE TITLE
Plugin failes with gradle version 8.1.1

### ISSUE THREAD

**Issue by Frisch12** [gradle/github-dependency-graph-gradle-plugin#62]
The plugin failes with this error message (unfortunately there is no more information in the gradle log output): 

```
* What went wrong:
Failed to stop service 'gitHubDependencyExtractorService'.
> The GitHubDependencyGraphPlugin plugin encountered errors while writing the dependency snapshot json file. Please report this issue at: https://github.com/gradle/github-dependency-graph-gradle-plugin/issues
```

**Comment by bigdaz** [comment]
The plugin is working correctly with Gradle 8.1.1 as demonstrated by this CI job: https://github.com/gradle/github-dependency-graph-gradle-plugin/actions/runs/5912408084/job/16035895646

Can you please run the build with `--stacktrace` and see if that provides a clue as to what's going wrong? Possibly you are not setting one of the [required environment variables](https://github.com/gradle/github-dependency-graph-gradle-plugin#required-environment-variables).

**Comment by Frisch12** [comment]
You're right. I was missing `GITHUB_JOB_CORRELATOR` and `GITHUB_JOB_ID`. Was still setting `GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR` and `GITHUB_DEPENDENCY_GRAPH_JOB_ID`.

Maybe there should be a better warning, when changing env-variables. As this project is still experimental it's ok, I think. 

Thank you for your help :)
